name: RPMBuild Yerase's TNEF

on:
  workflow_dispatch:

env:
  # SOURCEURL: 
  NAME: ytnef
  SPEC: /root/rpmbuild/SPECS/ytnef.spec
  VERSION: "2.1.2"
  RELEASE: "1"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        include:
          # - distro: centos
          #   version: 7
          #   image: rpmbuild-centos-7
          - distro: rockylinux
            version: 8
            image: rpmbuild-rockylinux-8
          - distro: rockylinux
            version: 9
            image: rpmbuild-rockylinux-9

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build Docker image
          run: |
                docker build \
                  --tag ${{ matrix.image }} \
                  --file dockerfiles/Dockerfile.${{ matrix.distro }}.${{ matrix.version }} \
                  .

        - name: Build RPM/SRPM packages
          run: |
                mkdir ${{ github.workspace }}/{RPMS,SRPMS}
                docker run --rm \
                  --volume ${{ github.workspace }}/RPMS:/root/rpmbuild/RPMS \
                  --volume ${{ github.workspace }}/SRPMS:/root/rpmbuild/SRPMS \
                  --volume ${{ github.workspace }}/SPECS:/root/rpmbuild/SPECS \
                  ${{ matrix.image }} \
                  bash -c "
                    curl -Lo /root/rpmbuild/SOURCES/${{ env.NAME }}-${{ env.VERSION }}.tar.gz https://github.com/Yeraze/ytnef/archive/v${{ env.VERSION }}/${{ env.NAME }}-${{ env.VERSION }}.tar.gz &&
                    rpmbuild -ba --define 'version ${{ env.VERSION }}' --define 'release ${{ env.RELEASE }}' ${{ env.SPEC }} &&
                    chown -R $(id -u):$(id -g) /root/rpmbuild/{RPMS,SRPMS}
                  "

        - name: Upload RPM/SRPM artifact
          if: success()
          uses: actions/upload-artifact@v4
          with:
            name: artifact-${{ matrix.distro }}.${{ matrix.version }}
            path: |
              ${{ github.workspace }}/RPMS/**/*.rpm
              ${{ github.workspace }}/SRPMS/*.src.rpm

  release:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download all RPM artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/
          merge-multiple: true

      - name: List artifact
        run: tree ${{ github.workspace }}/{RPMS,SRPMS}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}-${{ env.RELEASE }}
          name: Yerase's TNEF v${{ env.VERSION }}
          body: Build Yerase's TNEF Stream Reader on rockylinux 8, 9
          token: ${{ secrets.AUTO_RELEASE }}
          files: |
                  ${{ github.workspace }}/RPMS/x86_64/*.rpm
                  ${{ github.workspace }}/SRPMS/*.src.rpm


